/**
 * Service Worker — Workbox powered.
 *
 * Features:
 *   1. Precaches static assets (auto-generated by vite-plugin-pwa)
 *   2. Intercepts POST requests to /anc-visits — if they fail (offline),
 *      queues them in IndexedDB for replay via BackgroundSyncPlugin
 *   3. Listens for 'online' events and triggers replay of pending items
 *   4. Posts messages to the client for toast notifications
 */
/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// ── 1. Precache static assets ──────────────────────────────────────────
precacheAndRoute(self.__WB_MANIFEST);

// ── 2. Background sync for ANC visits POST ─────────────────────────────
const ancVisitSyncPlugin = new BackgroundSyncPlugin('anc-visits-queue', {
    maxRetentionTime: 24 * 60, // 24 hours (in minutes)
    onSync: async ({ queue }) => {
        let entry;
        while ((entry = await queue.shiftRequest())) {
            try {
                const response = await fetch(entry.request.clone());
                if (!response.ok) {
                    throw new Error(`Sync replay failed: ${response.status}`);
                }
                // Notify all clients about successful sync
                const clients = await self.clients.matchAll({ type: 'window' });
                for (const client of clients) {
                    client.postMessage({
                        type: 'SYNC_SUCCESS',
                        payload: {
                            url: entry.request.url,
                            timestamp: Date.now(),
                        },
                    });
                }
            } catch (error) {
                // Put the request back in the queue for retry
                await queue.unshiftRequest(entry);
                throw error; // Rethrow so BackgroundSync knows it failed
            }
        }
    },
});

// Intercept POST /anc-visits — if offline, Workbox queues for background sync.
registerRoute(
    ({ url, request }) =>
        request.method === 'POST' &&
        url.pathname.includes('/anc-visits'),
    new NetworkOnly({
        plugins: [ancVisitSyncPlugin],
    }),
    'POST',
);

// ── 3. Online event listener → notify clients ──────────────────────────
self.addEventListener('message', (event) => {
    if (event.data?.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

// When the SW activates, claim all clients immediately
self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});

// Notify clients when the browser comes back online
// (this supplements the Workbox BackgroundSync which uses the browser's
//  built-in Background Sync API when available)
self.addEventListener('fetch', () => {
    // no-op — handled by Workbox routes. Just ensures fetch events are captured.
});
